using System.Collections.Generic;

namespace OverEasy.TextInfo
{
    public class ObjectVariants
    {
        public static List<string> eggNames = new List<string>()
        {
            "Default",
            "Fire Comb",
            "Water Comb",
            "Lightning Comb",
            "Ice Comb",
            "Wind Comb",
            "Iron Comb",
            "Light Comb",
            "Wings",
            "Booster",
            "Paraloop",
            "Thorn Egg",
            "Speed Shoes",
            "Bomb",
            "Spring Shoes",
            "Circus Hat",
            "Psychic Hat",
            "Heart Hat",
            "Bat",
            "Crow",
            "Cipher",
            "Clippen",
            "Recky",
            "Richie",
            "Peliwan",
            "Runny",
            "Rabbish",
            "Rikol",
            "Kaboot",
            "Datch",
            "Glarin",
            "Boskus",
            "Oritta",
            "Biboo",
            "Gorilla",
            "Chameleon",
            "Mouse",
            "Turtle",
            "Lion",
            "Dice",
            "Super Fruit",
            "Tiger",
            "Sheep",
            "Hawk",
            "Fox",
            "Butterfly (Big)",
            "Stopwatch",
            "Butterfly (Small)",
            "1 Up",
            "Chick Bomb",
            "Sensor Bomb",
            "Chu Chu Rocket! Challenge",
            "NIGHTS SCORE ATTACK",
            "Billy Hatcher Hyper Shoot Easy",
            "Billy Hatcher Hyper Shoot",
            "Puyo Pop",
            "Sonic",
            "Tails",
            "Knuckles",
            "Chao",
            "Rappy",
            "Kapu Kapu",
            "NiGHTS",
            "Amigo",
            "Super Clippen",
            "Super Recky",
        };

        public static List<string> eggFileNames = new List<string>()
        {
            "none",
            "item_comb_fire.arc",
            "item_comb_water.arc",
            "item_comb_thunder.arc",
            "item_comb_ice.arc",
            "item_comb_wind.arc",
            "item_comb_iron.arc",
            "item_comb_light.arc",
            "item_wing.arc",
            "item_rocket.arc",
            "item_loop.arc",
            "item_spine.arc",
            "item_s_shoes.arc",
            "obj_ms_bomb.arc",
            "item_j_shoes.arc",
            "item_cap_circus.arc",
            "item_cap_psi.arc",
            "item_cap_heart.arc",
            "item_ani_bat.arc",
            "item_crow.arc",
            "ani_model_kiji.arc",
            "ani_model_pen.arc",
            "ani_model_saru.arc",
            "ani_model_hari.arc",
            "ani_model_dog.arc",
            "ani_model_kuma.arc",
            "ani_model_owl.arc",
            "ani_model_lion.arc",
            "ani_model_crab.arc",
            "ani_model_camel.arc",
            "ani_model_hawk.arc",
            "ani_model_bull.arc",
            "ani_model_orix.arc",
            "ani_model_devil.arc",
            "item_ani_gori.arc",
            "item_ani_leon.arc",
            "item_ani_rat.arc",
            "item_ani_turtle.arc",
            "item_ani_lion.arc",
            "item_dice.arc",
            "item_maxi.arc",
            "item_ani_tiger.arc",
            "item_ani_sheep.arc",
            "item_ani_hawk.arc",
            "item_ani_fox.arc",
            "item_ani_btfly.arc",
            "item_watch.arc",
            "item_ani_btfly2.arc",
            "item_extend.arc",
            "item_chickenbomb.arc",
            "item_sensorbomb.arc",
            "item_gba_chu.arc",
            "item_gba_nights.arc",
            "item_gba_egg.arc",
            "item_gba_egg.arc",
            "item_gba_puyo.arc",
            "ani_model_sonic.arc",
            "ani_model_tails.arc",
            "ani_model_knuckles.arc",
            "ani_model_chao.arc",
            "ani_model_lappy.arc",
            "ani_model_kapu.arc",
            "ani_model_nights.arc",
            "ani_model_amigo.arc",
            "ani_model_rare1.arc",
            "ani_model_rare2.arc",
        };

        public static List<string> fruits = new()
        {
            "(Apple)",
            "(Banana)",
            "(Cherry)",
            "(Melon)",
            "(Pineapple)",
            "(Strawberry)",
            "(Watermelon)",
        };

        public static List<string> zakoCrows = new()
        {
            "Dora (Cat)",
            "Gelly (Snake)",
            "Gray (Pufferfish)",
            "Anter (Ant)",
            "Batter (Bat)"
        };

        public static Dictionary<string, string> enemyFileMap = new()
        {
            {"ar_ene_am02.arc", "102" },
            {"ar_ene_ants_queen.arc", "106" },
            {"ar_ene_armadillo.arc", "10A"},
            {"ar_ene_bat.arc", "108"},
            {"ar_ene_bee.arc", "104"},
            {"ar_ene_blue_boss.arc", "200"},
            {"ar_ene_frog.arc", "109" },
            {"ar_ene_green_boss.arc", "900"},
            {"ar_ene_green_demo.arc", "600"},
            {"ar_ene_last_boss.arc", "700"},
            {"ar_ene_last_ex_boss.arc", "800"},
            {"ar_ene_lizard.arc", "105"},
            {"ar_ene_orange_boss.arc", "500"},
            {"ar_ene_orange_boss_map.arc", "500_Map"},
            {"ar_ene_penguin.arc", "107"},
            {"ar_ene_purple_boss.arc", "400"},
            {"ar_ene_red_boss.arc", "300"},
            {"ar_ene_snake.arc", "103"},
            {"ar_ene_yellow_boss.arc", "600"},
            {"ar_ene_yellow_boss_green.arc", "600_B"},
            {"ar_ene_zako_ant.arc", "101_3"},
            {"ar_ene_zako_bat.arc", "101_4"},
            {"ar_ene_zako_cat.arc", "101_0"},
            {"ar_ene_zako_fugu.arc", "101_2"},
            {"ar_ene_zako_snake.arc", "101_1"},
        };
    }
}
